services:
  - type: web
    name: crypto-clicker-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7802392783:AAFJGY04yCDwnh26vVLmsYlA9e8vWiaeaDg
